name: Release
on:
  push:
    branches:
      - master
    tags:
      - "!*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with: 
          node-version: '16'
      - name: install can-npm-publish
        run: |
          npm install can-npm-publish
          npm ci
      - name: check version and add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./release.sh
      - name: test
        run: npm run test
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
